### ISSUE TITLE
Add description for each script

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/OpexTemplate#1]
Actual ressources are not described in any way. A proper "how-to" must be included for each one, making them easier for developer to integrate in their own missions.

**Comment by ImplicitDeny** [comment]
Template usage will be documented in community elements.
A conversion to some kind of mod will also provide some help to users by configuring the template via GUI instead of script commands.

**Comment by ArwynFr** [comment]
You can consider using GitHub wiki feature if too much info for community files
