### ISSUE TITLE
Submarine placement not actualising

### ISSUE THREAD

**Issue by Seenri** [team-gsri/OpexTemplate#17]
When a player moves the submarine, then another player moves it again, the new placement doesn't actualise for everyone, resulting in players being teleporterd to different places, some at the old position, some at the new one.

**Comment by ImplicitDeny** [comment]
Probably spotted. Does the submarine itself also remain in the old place, or only the teleporting position ?

**Comment by ImplicitDeny** [comment]
Fixed in https://github.com/team-gsri/GSRI-Opex/commit/186dcf2cfb06f31b9ddbfa1c2cf22f3e34b85f8c
